### ISSUE TITLE
integrate with napalm-logs

### ISSUE THREAD

**Issue by afourmy** [afourmy/eNMS#1]
- create a napalm-logs webpage to configure and start napalm-logs
- use napalm-logs to retrieve the logs and store them in the SQL database
- create a webpage to display the logs (+ filter with criteria, order, etc) for each device

**Comment by paultech** [comment]
See #35 . 
I'd prefer to add a publisher to my existing napalm-logs that feeds into eNMS. I do not want eNMS to configure/control napalm-logs.

**Comment by afourmy** [comment]
napalm-logs support is currently too limited to be useful (low number of log type per OS). eNMS can already be configured to receive all Syslog messages. The event-driven automation system will be built on that.
