### ISSUE TITLE
Workflow failure edge, then recover back to success path

### ISSUE THREAD

**Issue by shorton3** [afourmy/eNMS#103]
Workflow enhancement to support a failure edge to a remediation/recovery job.  If the remediation/recovery job is successful, then success edge back to the original success path 'next job'.  The workflow can then continue on to overall success result.

**Comment by afourmy** [comment]
Done via the introduction of `Prerequisite` edge.
Docs: https://enms.readthedocs.io/en/latest/workflows/workflow_payload.html#workflow-payload
