### ISSUE TITLE
Oxidized/Rancid core functionality

### ISSUE THREAD

**Issue by shorton3** [afourmy/eNMS#104]
Enhance eNMS to support Oxidized functionality to store/search/retrieve device configs:
1. Poll network elements and download configuration when it changes
2. Ability to easily view current configuration of a device in the inventory
3. Search feature for any text in any configuration
4. For a given inventory device, view differences between different versions of configurations (perhaps this would rely on the proposed git archival service for git diff?)
5. Download configuration for a device to a local text file
6. External ReST API support to return a specified device's configuration as a JSON object (using device.name or device.ip_address)

**Comment by afourmy** [comment]
Done. Please reopen if something does not work.
Docs: https://enms.readthedocs.io/en/latest/inventory/configuration_management.html
