### ISSUE TITLE
Workflow-in-a-Workflow (sub-workflows)

### ISSUE THREAD

**Issue by shorton3** [afourmy/eNMS#105]
Enhancement for Workflow Builder to support workflows-in-a-workflow. That-is, add an already-defined sub-workflow to a main workflow.

Additionally, it would be good to be able to add the sub-workflow multiple times (ie. have multiple instances) in the main workflow. An example would be:  following the upgrade of each route processor, the same 5 service jobs needs to be run to validate the new state of the device. Rather than calling (and duplicating) those 5 jobs explicitly after each route processor upgrade, they can be put in a sub-workflow and called as a single entity after each route processor upgrade.

**Comment by shorton3** [comment]
Additionally, currently, double clicking a service job inside workflow builder gives 'edit the service'.  Please consider adding:  double clicking a sub-workflow job inside workflow builder to perform 'switch view to the sub-workflow' inside workflow builder.

**Comment by shorton3** [comment]
Also, it would be nice if workflow-in-a-workflow is added to one of the example workflows

**Comment by afourmy** [comment]
Done.
https://enms.readthedocs.io/en/latest/workflows/workflow_system.html
