### ISSUE TITLE
Modify NapalmGettersService to content_match key/value pairs

### ISSUE THREAD

**Issue by shorton3** [afourmy/eNMS#106]
NapalmGettersService current allows for content matching flat text or regex from the result returned from the device. Since napalm guarantees all results to be returned in dictionary format, please consider replacing this content_match a set of key:value pairs, or adding key/value pair matching as an added option for the match.   For example, user provides a dictionary with multiple key/value pairs. eNMS iterates (loop recursively) through the dictionary and checks that each key/value pair is SOMEWHERE in the resulting dictionary.

**Comment by afourmy** [comment]
Done.
Docs: https://enms.readthedocs.io/en/latest/services/default_services.html
