### ISSUE TITLE
Auto refresh for Workflow Builder

### ISSUE THREAD

**Issue by shorton3** [afourmy/eNMS#108]
Enhancement for Workflow Builder to allow auto refresh when multiple users are browsing a single Workflow int the Workflow Builder. Suggested functionality:  when workflow builder retrieves a workflow from eNMS, it also retrieves a timestamp of the last update to that workflow.  Periodically, the workflow builder sends ajax request to eNMS to ensure that its timestamp for the viewed workflow is still current. If it determines that the timestamp is stale, it will refresh the workflow view. Consider multiple users browsing the same workflow.  Then, one user updates that workflow.  The other users' browsers should then determine that they have stale views and refresh the workflow from eNMS.

I suggest a periodic polling interval of 15 seconds for checking the timestamp.

**Comment by afourmy** [comment]
Done: A Workflow will automatically update itself every 10 seconds if it has been modified.
Docs: https://enms.readthedocs.io/en/latest/workflows/workflow_system.html#automatic-refresh
