### ISSUE TITLE
External ReST interface for eNMS needs to be documented with Swagger/OpenAPI

### ISSUE THREAD

**Issue by shorton3** [afourmy/eNMS#113]
eNMS external ReST interface should be documented as a standard interface using Swagger/OpenAPI. This will allow user creating a client to interface to eNMS to use the standard interface file created from Swagger/OpenAPI to create stub code for sending ReST to eNMS.

**Comment by VeNoMouS** [comment]
An update on this? we are looking at using eNMS for automation but the lack of documentation around you're API is concerning.

**Comment by afourmy** [comment]
Done:
- new swagger folder here: https://github.com/afourmy/eNMS/tree/master/swagger
- docs for the REST API here: https://enms.readthedocs.io/en/latest/event_driven/rest_api.html
