### ISSUE TITLE
GoTTY debug terminal support telnet to alternative IP addresses

### ISSUE THREAD

**Issue by shorton3** [afourmy/eNMS#115]
Another use case that I have is that our devices are reachable via the device.ip_address using SSH. However, many of our devices are actually blade server chassis where there are 2 route processor/route engine nodes and a number of line/interface cards.  In this architecture, each RP/RE node has a terminal server connected to its serial console port, and these get used for certain types of debugging and in upgrades, etc. I have extended the eNMS inventory with custom properties: console_ip1 and console_ip2 for this purpose. It would be great if the GoTTY debug terminal configuration panel gave me an option to a) SSH or Telnet, and b) pick the default device.ip_address or use one of my custom property ip_addresses for the connection.  Thank you!

**Comment by afourmy** [comment]
Done.
Docs: https://enms.readthedocs.io/en/latest/inventory/web_connection.html#from-the-device-management-table
