### ISSUE TITLE
Why don't you integrate your efforts into an existing project?

### ISSUE THREAD

**Issue by misch42** [afourmy/eNMS#116]
Hi,
Very exciting project. But why do you build everything your own from the scratch? Why don't you integrate your ideas into an existing project like netbox? The graphing and your workflow management would integrate very cool into that project. On the other hand, they are very strong in asset management.

Michael Schwartzkopff

**Comment by afourmy** [comment]
Hi,

- I don't work for DigitalOcean or at a company that uses netbox, so I have no reason to spend time working on Netbox, or any other similar project (that in itself is reason enough)
- From a technical standpoint, eNMS and Netbox don't have much in common (Netbox tries to avoid front-end programming while eNMS is 50% javascript, + Flask versus Django)
- While I understand why the idea of having one project that does it all may be appealing, I don't agree with it and I think it's better to have a DCIM/IPAM solution that focuses on DCIM/IPAM, and a network automation solution that focuses on network automation.
- eNMS can be configured to use netbox API (pynetbox) to fetch whatever information it needs (not much in fact: IP addresses + GPS coordinates)
