### ISSUE TITLE
Environment Variable for setting Logging Level or Disable Logging

### ISSUE THREAD

**Issue by jmcgrath207** [afourmy/eNMS#117]
Hi Afourmy,

I was wondering if we could an environment variable for this line of code. Ideally, I was thinking something like `ENMS_LOG_LEVEL` and or `ENMS_LOG_ENABLE`

https://github.com/afourmy/eNMS/blob/master/eNMS/__init__.py#L115

While the default logging if usefully sometimes I have to debug the app with IPDB and the logging constantly gets in the way.

I am more than willing to create a pull request for this feature, just want to run it by you first.

Thanks,

John

**Comment by afourmy** [comment]
Hello @jmcgrath207 
Yes sure you're welcome to submit a PR for that.
Thanks

**Comment by afourmy** [comment]
I merged the PR this morning so I will close this issue; but you can reopen it if there is more to be done.
Thanks !
