### ISSUE TITLE
ERROR:  invalid input syntax for integer: "DatabaseBackupService"

### ISSUE THREAD

**Issue by fobrice** [afourmy/eNMS#126]
Hi,

   With eNMS under docker with postgresql, when we click on `Automation > Service management` or `Automation > Workflow builder` we get an error message (see screen capture at the end of message).

It seems that this is a message from [`/automation/get_service/DatabaseBackupService`](https://github.com/afourmy/eNMS/blob/a70471fe4d0c398646a5b04aae0eb2e793da85c7/eNMS/automation/routes.py#L90)

I think that the `fetch()` function generate an exception and I suggest to write this part like this:
```
def get_service(id_or_cls):
    service = None
    try:
        service = fetch('Service', id=id_or_cls)
    except:
        pass
    cls = service_classes[service.type if service else id_or_cls]
```

Regards,

Fabrice

Informations
--------------------

* docker logs
```
db_1     | 2019-02-06 16:14:43.281 UTC [29] ERROR:  invalid input syntax for integer: "DatabaseBackupService" at character 983
db_1     | 2019-02-06 16:14:43.281 UTC [29] STATEMENT:  SELECT "Job".type AS "Job_type", "Service".id AS "Service_id", "Job".id AS "Job_id", "Job".hidden AS "Job_hidden", "Job".name AS "Job_name", "Job".description AS "Job_description", "Job".multiprocessing AS "Job_multiprocessing", "Job".max_processes AS "Job_max_processes", "Job".number_of_retries AS "Job_number_of_retries", "Job".time_between_retries AS "Job_time_between_retries", "Job".positions AS "Job_positions", "Job".logs AS "Job_logs", "Job".status AS "Job_status", "Job".state AS "Job_state", "Job".credentials AS "Job_credentials", "Job".vendor AS "Job_vendor", "Job".operating_system AS "Job_operating_system", "Job".waiting_time AS "Job_waiting_time", "Job".creator_id AS "Job_creator_id", "Job".push_to_git AS "Job_push_to_git", "Job".send_notification AS "Job_send_notification", "Job".send_notification_method AS "Job_send_notification_method", "Job".mail_recipient AS "Job_mail_recipient" 
db_1     |      FROM "Job" JOIN "Service" ON "Job".id = "Service".id 
db_1     |      WHERE "Service".id = 'DatabaseBackupService' 
db_1     |       LIMIT 1
```

* screen capture
![enms-en-rouge](https://user-images.githubusercontent.com/11207495/52355886-81bf3000-2a33-11e9-8656-e8b9ae5fe183.png)

**Comment by afourmy** [comment]
Okay sounds good, but I would prefer to catch the exception explicitly (`Except DataError`, + import the DataError exception at the top of the file) because the `fetch` function might fail for a different reason, so we don't want to catch everything.
Do you want to send a PR to fix it ?

Thanks

**Comment by afourmy** [comment]
Thanks !
