### ISSUE TITLE
Ability to schedule jobs by time of day using APScheduler cron trigger?

### ISSUE THREAD

**Issue by shorton3** [afourmy/eNMS#130]
Is it possible to change APScheduler to use the linux cron style trigger to allow for specifying time-of-day tasks:  https://apscheduler.readthedocs/io/en/latest/modules/triggers/cron.html

I believe this will allow users to specify to run on Tuesdays at 9:12 AM, every week, for example.

Thank you!

**Comment by afourmy** [comment]
Done, hopefully for good this time :)
