### ISSUE TITLE
Configuration Management enhancements

### ISSUE THREAD

**Issue by shorton3** [afourmy/eNMS#131]
Can the Configuration Management 'Download' button be color coded:
- Transparent / Empty (as it currently is) - if no Config is available for the device
- Blue - if there is a Config available for the device (and thus available for download). 
This will take care of signifying if a Config exists in this instance

In Addition:
- How would you feel about adding a .yml file to each of the configurations that go into the 'configurations' git repository.  The drawback here is that the number of files in the repository would double...
- Instead of file 'device89-2611107a', there would also be a 'device89-2611107a.yml'
- device89-2611107a.yml would for example contain:
Last_failure: <timestamp>
Last_runtime: <timestamp>
Last_update: <timestamp>
Last_status:   <status string>
- Then, the .yml files could be read in to populate these fields in the database in other instances of eNMS

**Comment by afourmy** [comment]
Done
