### ISSUE TITLE
v3.10 fails on FreeSBD

### ISSUE THREAD

**Issue by dBitech** [afourmy/eNMS#132]
[root@nms ~/eNMS-3.10]# pip-3.6 install -r dev_requirements
snip..  But installs with no errors.  (also note there is no requirements.txt in the v3.10 release file)

    [root@nms ~/eNMS-3.10]# flask run --host=0.0.0.0
     * Serving Flask app "app.py"
     * Environment: production
       WARNING: Do not use the development server in a production environment.
       Use a production WSGI server instead.
     * Debug mode: off
    Usage: flask run [OPTIONS]
    
    Error: While importing "app", an ImportError was raised:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 338, 
    in dbapi
        from pysqlite2 import dbapi2 as sqlite
    ModuleNotFoundError: No module named 'pysqlite2'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):

**Comment by afourmy** [comment]
There is a `requirements.txt` in 3.10 (otherwise Travis would fail); you should make sure all requirements are properly installed.

**Comment by dBitech** [comment]
Hmm, i just refetchd the .tar.gz and it's in there, strange;

    [root@nms ~/eNMS-3.10]# uname -a
    FreeBSD nms 12.0-RELEASE-p2 FreeBSD 12.0-RELEASE-p2 GENERIC  amd64

    [root@nms ~/eNMS-3.10]# python -Vv
    Python 3.6.8

    [root@nms ~/eNMS-3.10]# pip-3.6 install -r requirements.txt
    Requirement already satisfied: apscheduler in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 1))
    Requirement already satisfied: dicttoxml in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 2))
    Requirement already satisfied: flask in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 3))
    Requirement already satisfied: flask_httpauth in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 4))
    Requirement already satisfied: flask_login in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 5))
    Requirement already satisfied: flask_mail in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 6))
    Requirement already satisfied: flask-restful in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 7))
    Requirement already satisfied: flask_sqlalchemy in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 8))
    Requirement already satisfied: flask_wtf in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 9))
    Requirement already satisfied: gitpython in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 10))
    Requirement already satisfied: gunicorn in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 11))
    Requirement already satisfied: hvac in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 12))
    Requirement already satisfied: jinja2 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 13))
    Requirement already satisfied: ldap3 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 14))
    Requirement already satisfied: napalm in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 15))
    Requirement already satisfied: netmiko in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 16))
    Requirement already satisfied: pathlib in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 17))
    Requirement already satisfied: psutil in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 18))
    Requirement already satisfied: psycopg2 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 19))
    Requirement already satisfied: pynetbox in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 20))
    Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 21))
    Requirement already satisfied: slackclient in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 22))
    Requirement already satisfied: simplekml in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 23))
    Requirement already satisfied: tacacs_plus in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 24))
    Requirement already satisfied: wtforms in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 25))
    Requirement already satisfied: xlrd in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 26))
    Requirement already satisfied: xlwt in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 27))
    Requirement already satisfied: xmltodict in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 28))
    Requirement already satisfied: tzlocal>=1.2 in /usr/local/lib/python3.6/site-packages (from apscheduler->-r requirements.txt (line 1))
    Requirement already satisfied: pytz in /usr/local/lib/python3.6/site-packages (from apscheduler->-r requirements.txt (line 1))
    Requirement already satisfied: setuptools>=0.7 in /usr/local/lib/python3.6/site-packages (from apscheduler->-r requirements.txt (line 1))
    Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.6/site-packages (from apscheduler->-r requirements.txt (line 1))
    Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.6/site-packages (from flask->-r requirements.txt (line 3))
    Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.6/site-packages (from flask->-r requirements.txt (line 3))
    Requirement already satisfied: Werkzeug>=0.14 in /usr/local/lib/python3.6/site-packages (from flask->-r requirements.txt (line 3))
    Requirement already satisfied: blinker in /usr/local/lib/python3.6/site-packages (from flask_mail->-r requirements.txt (line 6))
    Requirement already satisfied: aniso8601>=0.82 in /usr/local/lib/python3.6/site-packages (from flask-restful->-r requirements.txt (line 7))
    Requirement already satisfied: SQLAlchemy>=0.8.0 in /usr/local/lib/python3.6/site-packages (from flask_sqlalchemy->-r requirements.txt (line 8))
    Requirement already satisfied: gitdb2>=2.0.0 in /usr/local/lib/python3.6/site-packages (from gitpython->-r requirements.txt (line 10))
    Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.6/site-packages (from hvac->-r requirements.txt (line 12))
    Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/site-packages (from jinja2->-r requirements.txt (line 13))
    Requirement already satisfied: pyasn1>=0.1.8 in /usr/local/lib/python3.6/site-packages (from ldap3->-r requirements.txt (line 14))
    Requirement already satisfied: pyIOSXR>=0.53 in /usr/local/lib/python3.6/site-packages (from napalm->-r requirements.txt (line 15))
    Requirement already satisfied: cffi>=1.11.3 in /usr/local/lib/python3.6/site-packages (from napalm->-r requirements.txt (line 15))
    Requirement already satisfied: pyeapi>=0.8.2 in /usr/local/lib/python3.6/site-packages (from napalm->-r requirements.txt (line 15))
    Requirement already satisfied: nxapi-plumbing>=0.5.2 in /usr/local/lib/python3.6/site-packages (from napalm->-r requirements.txt (line 15))
    Requirement already satisfied: scp in /usr/local/lib/python3.6/site-packages (from napalm->-r requirements.txt (line 15))
    Requirement already satisfied: future in /usr/local/lib/python3.6/site-packages (from napalm->-r requirements.txt (line 15))
    Requirement already satisfied: junos-eznc>=2.2.0 in /usr/local/lib/python3.6/site-packages (from napalm->-r requirements.txt (line 15))
    Requirement already satisfied: netaddr in /usr/local/lib/python3.6/site-packages (from napalm->-r requirements.txt (line 15))
    Requirement already satisfied: paramiko>=2.4.2 in /usr/local/lib/python3.6/site-packages (from napalm->-r requirements.txt (line 15))
    Requirement already satisfied: textfsm in /usr/local/lib/python3.6/site-packages (from napalm->-r requirements.txt (line 15))
    Requirement already satisfied: pyserial in /usr/local/lib/python3.6/site-packages (from netmiko->-r requirements.txt (line 16))
    Requirement already satisfied: websocket-client<0.55.0,>=0.35 in /usr/local/lib/python3.6/site-packages (from slackclient->-r requirements.txt (line 22))
    Requirement already satisfied: smmap2>=2.0.0 in /usr/local/lib/python3.6/site-packages (from gitdb2>=2.0.0->gitpython->-r requirements.txt (line 10))
    Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests>=2.21.0->hvac->-r requirements.txt (line 12))
    Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests>=2.21.0->hvac->-r requirements.txt (line 12))
    Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests>=2.21.0->hvac->-r requirements.txt (line 12))
    Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests>=2.21.0->hvac->-r requirements.txt (line 12))
    Requirement already satisfied: lxml>=3.2.4 in /usr/local/lib/python3.6/site-packages (from pyIOSXR>=0.53->napalm->-r requirements.txt (line 15))
    Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.11.3->napalm->-r requirements.txt (line 15))
    Requirement already satisfied: ncclient>=0.5.4 in /usr/local/lib/python3.6/site-packages (from junos-eznc>=2.2.0->napalm->-r requirements.txt (line 15))
    Requirement already satisfied: cryptography>=1.5 in /usr/local/lib/python3.6/site-packages (from paramiko>=2.4.2->napalm->-r requirements.txt (line 15))
    Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python3.6/site-packages (from paramiko>=2.4.2->napalm->-r requirements.txt (line 15))
    Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.6/site-packages (from paramiko>=2.4.2->napalm->-r requirements.txt (line 15))
    Requirement already satisfied: selectors2>=2.0.1 in /usr/local/lib/python3.6/site-packages (from ncclient>=0.5.4->junos-eznc>=2.2.0->napalm->-r requirements.txt (line 15))
    Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python3.6/site-packages (from cryptography>=1.5->paramiko>=2.4.2->napalm->-r requirements.txt (line 15))

`[root@nms ~/eNMS-3.10]# !fla
flask run --host=0.0.0.0
 * Serving Flask app "app.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 338, in dbapi
    from pysqlite2 import dbapi2 as sqlite
ModuleNotFoundError: No module named 'pysqlite2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/root/eNMS-3.10/app.py", line 5, in <module>
    from eNMS import create_app
  File "/root/eNMS-3.10/eNMS/__init__.py", line 10, in <module>
    from eNMS.extensions import (
  File "/root/eNMS-3.10/eNMS/extensions.py", line 39, in <module>
    "apscheduler.job_defaults.max_instances": "3",
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 126, in configure
    self._configure(config)
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 741, in _configure
    jobstore = self._create_plugin_instance('jobstore', plugin, value)
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 906, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/local/lib/python3.6/site-packages/apscheduler/jobstores/sqlalchemy.py", line 52, in __init__
    self.engine = create_engine(url, **(engine_options or {}))
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 423, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 343, in dbapi
    raise e
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 341, in dbapi
    from sqlite3 import dbapi2 as sqlite  # try 2.5+ stdlib name.
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
`

**Comment by afourmy** [comment]
I'll close because this is an environment problem, not an eNMS one.
Try this perhaps: https://stackoverflow.com/questions/1210664/no-module-named-sqlite3
