### ISSUE TITLE
Adding napalm drivers. Mechanism for this?

### ISSUE THREAD

**Issue by robp2175** [afourmy/eNMS#139]
We are a brocade shop here so I need to add napalm-ruckus-fastiron
 driver. I have added it to requirements.txt and then docker-compose build. eNMS does not recognize in the UI that the driver exists and I have not found documentation for this. I looked around the UI and the DB, but was unable where to find where to add this. Thank you again.

**Comment by afourmy** [comment]
It is in the documentation, here: https://enms.readthedocs.io/en/latest/services/default_services.html#napalm-configuration-service
You have to update the SUPPORTED_DRIVER list in napalm.

**Comment by robp2175** [comment]
So, I abandoned Docker because it added a level of complexity that I don't need right now. I added the driver to the file after installing it

`
pip3 install napalm-ruckus-fastiron
 /usr/local/lib/python3.7/dist-packages/napalm/_SUPPORTED_DRIVERS.py`


and it still does not show up in the list when I run with boot.sh
It does show up when I run with flask

**Comment by afourmy** [comment]
@robp2175 the only difference between flask and boot.sh is that boot.sh uses gunicorn, so my guess here is that gunicorn does not use python3.7 but another version on your system.
Can you check if you have multiple versions of python on your system, and make sure gunicorn uses the right one ?

**Comment by robp2175** [comment]
You were on the money. Gunicorn was indeed using a different python version. Thank you for your patience. I can report the system is up and wokring. A few small things I found that you might want to add to the docs (unless you already did and I missed it):
gotty was not executable
`chmod +x applications/gotty`
sshpass was not installed by default in my distro (Ubuntu 18.04)
`apt install sshpass`
I needed to logon to each switch manually from the command line to add them to known_hosts (for people that connect using ssh) This needs to be done even before you try and use sshpass for the first time. 
If you have mentioned any of this and I missed it I apologize. Your excellent documentation and setup procedure made this quite easy to debug with some help from you. Thanks a bunch.

**Comment by afourmy** [comment]
@robp2175 I implemented a mechanism to bypass `known_hosts`, here: https://enms.readthedocs.io/en/latest/inventory/web_connection.html#ignore-fingerprint-prompt
have you tried it ?

**Comment by afourmy** [comment]
Regarding sshpass and gotty +x, both are already mentioned in the docs:
gotty: https://enms.readthedocs.io/en/latest/inventory/web_connection.html#installation
sshpass: https://enms.readthedocs.io/en/latest/inventory/web_connection.html#from-the-device-management-table
