### ISSUE TITLE
Support for idempotent workflows

### ISSUE THREAD

**Issue by shorton3** [afourmy/eNMS#140]
We have a few devices that are unstable from the vendor when performing upgrades, etc. In the case of such workflows, it would be great to be able to have a workflow start, die somewhere in the middle of the workflow, but then be able to restart/re-run the workflow without it again performing 'already completed' service instance steps.  Ansible behaves like this (refer to Ansible Idempotence) and uses .retry files to track state of partially run workflows.

**Comment by afourmy** [comment]
- Right-click menu in workflow builder to 'start from here'
- access the payload contents for the previously run services.

**Comment by afourmy** [comment]
Done.
