### ISSUE TITLE
Enhancements for viewing results

### ISSUE THREAD

**Issue by shorton3** [afourmy/eNMS#141]
There are several enhancements to viewing service instance and workflows results that we feel could improve the user experience:
1. View by device: In order list of services run on a specific device
2. View by service: In order list of devices affected by the service
3. Reduce the overwhelming amount of data by:
  a. Collapsable sections: Moving around in the data is overwhelming
  b. Filtering by device / service / pass-fail
  c. Jump to next/previous device, service, pass-fail (with auto collapse/expand)

**Comment by afourmy** [comment]
Implemented in eNMS 3.15.
