### ISSUE TITLE
Support for YaQL query language in service fields for extraction and validation

### ISSUE THREAD

**Issue by shorton3** [afourmy/eNMS#143]
Would it be possible to support the YaQL query language in the form fields of services?  This would allow extra freedom beyond regular expressions when extracting data from complex dictionaries and lists, as well as for performing validation without resorting to writing custom services.

**Comment by shorton3** [comment]
As an additional part:  then could YaQL be used to extract / identify targets for services from previous service results?  The use case here would be:  create a workflow with a first service instance that retrieves a device config section, then in a subsequent service instance use a YaQL query to extract route endpoints or other config artifacts as the targets for this subsequent service.

**Comment by afourmy** [comment]
Done.
