### ISSUE TITLE
Improvements to the realtime logging mechanism

### ISSUE THREAD

**Issue by shorton3** [afourmy/eNMS#145]
This first implementation suffers from some database / threadsafety issues. Adding each logline to the database is very hard on a distributed database / distributed worker model.  Instead, recommend  using a logstream where:
a) One or more UI clients save the stream to a file
b) UI presents a view of the file (or stream) in a tail -f fashion
c) Log is saved to the database after service completion, or on checkpoints

**Comment by afourmy** [comment]
Implemented in eNMS 3.15.
