### ISSUE TITLE
BUG: NetmikoDataExtractionService

### ISSUE THREAD

**Issue by leonardo-munhoz** [afourmy/eNMS#147]
Bug after update version Version 3.13 

"result": "Traceback (most recent call last):
  File "/data/eNMS-3.13/eNMS/models/automation.py", line 271, in get_results
    results = self.job(payload, device, parent)
  File "/data/eNMS-3.13/eNMS/services/data_extraction/netmiko_data_extraction.py", line 51, in job
    netmiko_connection = self.netmiko_connection(device)
TypeError: netmiko_connection() missing 1 required positional argument: 'parent'",
        "success": false

**Comment by afourmy** [comment]
@leonardo-munhoz Thanks for reporting this bug.
You can fix this bug by replacing this line: https://github.com/afourmy/eNMS/blob/master/eNMS/services/data_extraction/netmiko_data_extraction.py#L51 with `netmiko_connection = self.netmiko_connection(device, parent)`

Note that this service is going to be removed soon. Instead, you can use the NetmikoValidationService to get some data from the device, and then use a PayloadExtractionService to extract data with regex/textfsm/yaql. We're moving to a more workflow-oriented model where services do only one thing (get data from device, or postprocess data, but not both).

**Comment by leonardo-munhoz** [comment]
It worked
I'll test your recommendation too.
thank you
