### ISSUE TITLE
BUG: Work Builder job objects

### ISSUE THREAD

**Issue by leonardo-munhoz** [afourmy/eNMS#148]
Workflow Builder:  job position move and dont cant fix correct place

![workflow set](https://user-images.githubusercontent.com/40440690/60388955-7676aa80-9a8f-11e9-9b4f-c7f1b6d5443e.JPG)
![work flow page reload](https://user-images.githubusercontent.com/40440690/60388956-7c6c8b80-9a8f-11e9-815f-e733301061f3.JPG)

**Comment by afourmy** [comment]
It works fine for me, I cannot reproduce it.
Each time you make a change to the workflow, eNMS will send a "save_positions" POST request to the server to save all positions (in the logs, it looks like that: `06-29-2019 22:01:14 INFO     127.0.0.1 - - [29/Jun/2019 22:01:14] "POST /save_positions/48 HTTP/1.0" 200 -`).
For some reasons, positions are not saved in your case, but I suspect this could have something to do with your environment (connection with the database ?) and not the code.
Perhaps I can help more if you can find a way to reproduce this problem consistently, or if you see something wrong in the logs.

**Comment by leonardo-munhoz** [comment]
Sorry,

Work fine now 

my var in 100%   :-(

/dev/mapper/vgSystem-lvVAR
                      4.0G  4.0G     0 100% /var
