### ISSUE TITLE
AttributeError: 'Workflow' object has no attribute 'multiprocessing'

### ISSUE THREAD

**Issue by conanxu** [afourmy/eNMS#152]
I got an error message when I use workflow management. And my job is always in running status.

enms_1   | 172.23.0.3 - - [14/Jul/2019:16:32:09 +0800] "POST /filtering/workflow HTTP/1.0" 500 290 "http://192.168.56.11/table/workflow" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
enms_1   | [2019-07-14 16:32:17 +0800] [7] [DEBUG] POST /filtering/workflow
enms_1   | 07-14-2019 16:32:17 ERROR    Exception on /filtering/workflow [POST]
enms_1   | Traceback (most recent call last):
enms_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
enms_1   |     response = self.full_dispatch_request()
enms_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
enms_1   |     rv = self.handle_user_exception(e)
enms_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
enms_1   |     return original_handler(e)
enms_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
enms_1   |     reraise(exc_type, exc_value, tb)
enms_1   |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
enms_1   |     raise value
enms_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
enms_1   |     rv = self.dispatch_request()
enms_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
enms_1   |     return self.view_functions[rule.endpoint](**req.view_args)
enms_1   |   File "/eNMS/routes.py", line 47, in decorated_function
enms_1   |     return function(*args, **kwargs)
enms_1   |   File "/eNMS/routes.py", line 221, in route
enms_1   |     result = getattr(controller, f)(*args, request.form)
enms_1   |   File "/eNMS/controller/base.py", line 467, in filtering
enms_1   |     .offset(int(kwargs["start"]))
enms_1   |   File "/eNMS/controller/base.py", line 466, in <listcomp>
enms_1   |     for obj in result.limit(int(kwargs["length"]))
enms_1   |   File "/eNMS/controller/base.py", line 464, in <listcomp>
enms_1   |     [getattr(obj, property) for property in properties]
enms_1   |   File "/eNMS/database/base.py", line 32, in __getattribute__
enms_1   |     return super().__getattribute__(property)
enms_1   |   File "/eNMS/models/automation.py", line 119, in progress
enms_1   |     if self.is_running and not self.multiprocessing:
enms_1   |   File "/eNMS/database/base.py", line 32, in __getattribute__
enms_1   |     return super().__getattribute__(property)
enms_1   | AttributeError: 'Workflow' object has no attribute 'multiprocessing'

**Comment by afourmy** [comment]
Just pushed a fix in the master branch.
From what I can tell, this was only a display issue, it shouldn't cause your workflow to be stuck in the running status.
You can reset all statuses in the admin page (admin / administration > miscellaneous > reset job statuses)

**Comment by conanxu** [comment]
thx, my workflow has been turn to normal after reseting job statues. I will close this issue.

**Comment by afourmy** [comment]
What I meant is that there is likely something else that goes wrong with your workflow, otherwise you wouldn't have had to reset its status. But it is not related to this bug you reported.
If you run your workflow one more time, I suspect it will also be stuck in the running status for some reason.
