### ISSUE TITLE
Ajax Error: Datatables warning id=table

### ISSUE THREAD

**Issue by dBitech** [afourmy/eNMS#155]
After starting up eNMS with no default data, and attempting to create service work flows,

Receive the following.:

DataTables warning: table id=table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

This error loops,  and I'm unable to create any workflows.

**Comment by afourmy** [comment]
The master branch works so it must have something to do with you envionment.
Can you try:

- emptying you browser cache
- deleting and recreating the database if it wasn't empty when you started eNMS ?

**Comment by afourmy** [comment]
Can't reproduce, everything seems to work as intended.
