### ISSUE TITLE
Custom Parameters via API

### ISSUE THREAD

**Issue by Geertkok1** [afourmy/eNMS#158]
Does eNMS currently support setting custom parameters via an API request?

For example:
- Create a service to add something to a config of a device
- Call that service via the API and set parameters from the API call, e.g. commands to be added to the config. 
- Have eNMS execute the service with the parameters that are set in the API request

Can eNMS currently do this via workflow or does eNMS currently not support his?

**Comment by afourmy** [comment]
Yes it does support all this.
You can run a service / workflow from the REST API with this endpoint: https://enms.readthedocs.io/en/latest/events/rest_api.html#run-a-service-or-a-workflow

You can use the payload to pass any data you want to the job (the payload can be used in a string with the variable substitution mechanism: `{{payload[...]}}` (https://enms.readthedocs.io/en/latest/services/service_system.html#variable-substitution)
You can also overwrite any service parameter by including it in the REST data.

For example, a netmiko service called with the following data:

```
{
  "name": "netmiko_check_vrf_test",
  "async": false,
  "devices": ["Washington"],
  "command": "show ip route",
  "payload": {"aid": "1-2-3", "user_identified_key": "user_identified_value"}
}
```

will send the command `show ip route` even though it is configured to run another command in the UI: the `command` parameter is overridden
