### ISSUE TITLE
Display netmiko logs on the website

### ISSUE THREAD

**Issue by afourmy** [afourmy/eNMS#27]
When netmiko is used to send a script with wrong commands, there is no exception as the ssh connection to the device is working: netmiko logs are the only way to find out what went wrong.
This logs must be saved in a python variable and displayed on the website by redirecting the log stream to a fake sys.stdout StringIO() object.

Something like that:

```logging.basicConfig(filename=log_filename, level=logging.DEBUG)
logger = logging.getLogger("netmiko")
sys.stdout = netmiko_out = StringIO()
ch = logging.StreamHandler(netmiko_out)
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)
```

This will let the user know why the script is wrong.

**Comment by longdn84** [comment]
Could you change the code to display log from the latest is first, the oldest is the end (currently is vice versa) due to users usually take care the newest information :)

**Comment by afourmy** [comment]
The logs are ordered from 3.6+ and eNMS is py3.6+ only so the log ordering issue no longer exists.
As for displaying netmiko logs on the website, that would mean storing the logs in the database, which is probably a bad idea.
