### ISSUE TITLE
make SSH connection / putty work on a remote unix jump server

### ISSUE THREAD

**Issue by afourmy** [afourmy/eNMS#28]
Right now, the SSH connection to a device only works on Windows as it uses subprocess.Popen to call Putty.exe. With Unix, the ssh command must be called with subprocess.Popen or subprocess.call.

If eNMS is installed on a jump server, the SSH connection should also work if X11 forwarding / Xming is enabled on the SSH connection to the jump server.

**Comment by afourmy** [comment]
Add support for webssh2: https://github.com/billchurch/WebSSH2
Two options:
- let the user import a .json files containing webssh2 parameters
- implement a flask form to configure webssh2 directly from withing eNMS

**Comment by paultech** [comment]
Additional suggestions:
https://github.com/stuicey/SSHy (Very little configuration/overhead)
https://github.com/liftoff/GateOne (Feature rich but requires running a python proxy as with WebSSH2)

**Comment by shorton3** [comment]
I would like this feature too. Here are some observations:
- General information regarding web-based SSH: https://en.wikipedia.org/wiki/Web-based_SSH
- SSHy mentioned above appears to implement 'lite' terminal emulation on the client/browser side. It even says that its a pseudo terminal that supports a subset of functionality. My fear here is that network device terminals typically need max flexibility.
- Both Chrome Secure Shell extension (google 'Secure Shell Extension' in the chrome web store) and GoTTy (https://github.com/yudai/gotty) make use of the Chrome terminal emulator 'hterm'.  Both of these solutions would make the solution dependent on Chrome browser...?? Appears to be broad support for these.
- wetty is another project that uses hterm: https://github.com/krishnasrinivas/wetty
- Here's a link to xterm.js based products. SSHy and GoTTY are both listed here. https://xtermjs.org/
- Gateone appears to be a commercial product; looks good but the licensing is undesirable (to me). However, this appears to be one of the only solutions that does the terminal emulation on the server side (see discussion in the above wiki link).

**Comment by afourmy** [comment]
@paultech this is done, and I updated the doc here : https://enms.readthedocs.io/en/develop/objects/webssh.html

I use GoTTY for the implementation.
