### ISSUE TITLE
Properly hash passwords

### ISSUE THREAD

**Issue by Eising** [afourmy/eNMS#31]
Hi,

Could you implement a secure password hashing? I'm not really comfortable with the fact that passwords are visible in plain text in a sqlite file-based database.

**Comment by afourmy** [comment]
Hello,

I intend to switch from SQLite to PostgreSQL (see https://github.com/afourmy/eNMS/issues/20). I will make sure during the transition that passwords are properly encrypted (by default, with a PostgreSQL, I think they should be).

**Comment by afourmy** [comment]
I changed my mind: this was easy to do so I did it. passwords are now hashed with the PBKDF2-SHA256 algorithm in the SQLite database. The changes are in the master branch (and will be in the next release). You can test it and if anything in wrong, you can reopen this issue
