### ISSUE TITLE
Edit an object

### ISSUE THREAD

**Issue by afourmy** [afourmy/eNMS#33]
Right now, there is no way to edit an object other than deleting it and recreating it. 
To be implemented: user-friendly way to edit an object

**Comment by tlofreso** [comment]
FYI, uploading spreadsheet with object changes will work. assuming this will just overwrite any object with the same name in the DB?

**Comment by afourmy** [comment]
Yes, I will make sure it works for both manual creation and speadsheet import. I think it already works for nodes, and I will finish the "link" part tonight :)

**Comment by afourmy** [comment]
edit works for both Excel import + manual edition from the GUI now.
