### ISSUE TITLE
Syslog server feature

### ISSUE THREAD

**Issue by afourmy** [afourmy/eNMS#35]
Make eNMS able to act as a syslog server:
- receive the logs and store them in the database
- advanced regex-based filtering of the logs (filter per device, filter per keyword, a keyword can be a string or a regex)
- parse the logs to retrieve the time and give the user a way to look at the log from start time til end time (bootstrap)

**Comment by paultech** [comment]
What about a generic abstract event/log interface?
I personally would prefer to tie into GrayLog for my logging, I have existing infrastructure and don't require eNMS to act as the solution to every problem.

fetchLogs(devicename,severity = ALL,from=1d,to=now()) returns JSON of events to be cached

**Comment by afourmy** [comment]
Done.
