### ISSUE TITLE
Workflow step by step

### ISSUE THREAD

**Issue by sproot1979** [afourmy/eNMS#366]
Hello,

Is there such a mode for workflow, when services in it are performed in manual mode step by step? The second question: is it possible to switch from service to service in workflow using a manual trigger?

**Comment by afourmy** [comment]
No, there is no such mode. But you can get the same behavior by deleting the workflow edge where you want the workflow to stop, then use the "Restart from here" feature with the previous runtime.
Closing as no customer request for this.
