### ISSUE TITLE
eNMS "/" redirect to "/login" and "/login" to "/dashboard" through http

### ISSUE THREAD

**Issue by lordofire** [afourmy/eNMS#367]
Hi there,

I have a question regarding using eNMS in kubernetes. I have configured the ingress nginx and https certificates correctly and everything works well in the docker environment + kubernetes. However, there seems to be a problem on the login redirection. Whenever I use `https://<enms-fqdn>/` to access the eNMS, it will prompt a failure like the following:

![image](https://user-images.githubusercontent.com/3886335/138176612-1027050c-c916-427f-b96c-08b4f63d9474.png)

From the http response I received from the client side, I do see that there is a 301 redirect response to `http://<enms-fqdn>/login` instead of `https://<enms-fqdn>/login`, leading to the above failure. The same thing happens when I finished logging in and go to the dashboard page, where it returns `http://<enms-fqdn>/dashboard` instead of `https://<enms-fqdn>/dashboard`. I do checked the code, and I have tried to configure `settings.json` by setting the fqdn through `address` field, but still I'm not able to address this issue.

Please help, thanks.

**Comment by afourmy** [comment]
There is no problem with the login redirection, it works fine. The redirection is implemented using `flask.redirect`: whether it uses http or https entirely depends on your environment.
The `address` field in `settings.json` is only used for the mail notifications and the web SSH feature, not for the standard HTTP stuff, that is handled by Flask.
I don't know how to fix your problem, I have no experience with Kubernetes, but eNMS is not the issue.
