### ISSUE TITLE
WTForms incompatibility with version 3.0.0

### ISSUE THREAD

**Issue by dmcken** [afourmy/eNMS#369]
I am getting an import error on an Ubuntu 20.04 server attempting to install eNMS (I have to manually "from eNMS.server import server as app" from a python shell to get the traceback):

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/airlink/eNMS/eNMS/__init__.py", line 5, in <module>
    from eNMS.forms import form_factory
  File "/home/airlink/eNMS/eNMS/forms.py", line 12, in <module>
    from eNMS.fields import (
  File "/home/airlink/eNMS/eNMS/fields.py", line 17, in <module>
    from wtforms.widgets.core import HTMLString
ImportError: cannot import name 'HTMLString' from 'wtforms.widgets.core' (/usr/local/lib/python3.8/dist-packages/wtforms/widgets/core.py)
```

Workaround:
pip3 install WTForms==2.3.3
after installing from requirements.txt
or
Edit build/requirements/requirements.txt and set "wtforms<=2.3.3")

**Comment by jsmith7735** [comment]
@dmcken I ran into this issue as well today. I was able to resolve this using this method.

I resolved by modifying Line 17 in the file /var/www/eNMS/eNMS/fields.py `from wtforms.widgets import HTMLString` to `from markupsafe import Markup `I also updated line 159 to reflect `Markup` instead of `HTMLString`

This may be a better long-term solution because I believe the HTMLString will be depricated in a future release.

**Comment by dmcken** [comment]
I agree it would be easier, I'm not familiar with WTForms and if the actual logic of the markup module changed from HTMLString as you could just as easily do:

```
try:
  from wtforms.widgets import HTMLString
except ImportError:
  from markupsafe import Markup as HTMLString
```

To keep the changes to a minimum and be backward compatible. This of course assumes HTMLString and Markup are identical that we can use them interchangeably and they won't diverge in the future.

**Comment by bjazzi** [comment]
> @dmcken I ran into this issue as well today. I was able to resolve this using this method.
> 
> I resolved by modifying Line 17 in the file /var/www/eNMS/eNMS/fields.py `from wtforms.widgets import HTMLString` to `from markupsafe import Markup `I also updated line 159 to reflect `Markup` instead of `HTMLString`
> 
> This may be a better long-term solution because I believe the HTMLString will be depricated in a future release.

Thanks, you make my day!!

**Comment by bjazzi** [comment]
> @dmcken I ran into this issue as well today. I was able to resolve this using this method.
> 
> I resolved by modifying Line 17 in the file /var/www/eNMS/eNMS/fields.py `from wtforms.widgets import HTMLString` to `from markupsafe import Markup `I also updated line 159 to reflect `Markup` instead of `HTMLString`
> 
> This may be a better long-term solution because I believe the HTMLString will be depricated in a future release.

Thanks you. You made my day/night!

**Comment by afourmy** [comment]
eNMS now imports markup => wtforms>=3 required
