### ISSUE TITLE
Task not run

### ISSUE THREAD

**Issue by buzzzo** [afourmy/eNMS#375]
Last version deployed here:4.0.0 (github)
Ems service correctly run and execute the services manually correctly.

I've deployed scheduler:

xport ENMS_ADDR="http://127.0.0.1:5000"
export ENMS_PASSWORD="admin"
export ENMS_USER="admin"
export VERIFY_CERTIFICATE=0
cd /opt/enms/scheduler
exec gunicorn --config gunicorn.py scheduler:scheduler  2>&1

And from "Automation->scheduling" i'm correctly see it's connected.
I then schedule a task and it seems to be correctlye executed from scheduler log:

022-02-04 12:18:13,027 DEBUG    Looking for jobs to run
2022-02-04 12:18:13,030 INFO     Running job "Scheduler.run_service (trigger: interval[0:01:00], next run at: 2022-02-04 12:19:13 CET)" (scheduled at 2022-02-04 12:18:13+01:00)
2022-02-04 12:18:13,034 DEBUG    Starting new HTTP connection (1): 127.0.0.1:5000
2022-02-04 12:18:13,040 DEBUG    http://127.0.0.1:5000 "POST /rest/run_task/1 HTTP/1.1" 400 142
2022-02-04 12:18:13,042 INFO     Job "Scheduler.run_service (trigger: interval[0:01:00], next run at: 2022-02-04 12:19:13 CET)" executed successfully

Except for the fact that the task in NOT executed at All.

On the enms side logs tell:

==> current <==
@4000000061fd0e1301e803a4 [2022-02-04 12:29:13 +0100] [113279] [DEBUG] POST /rest/run_task/1
@4000000061fd0e1301fba314 2022-02-04 12:29:13,033 INFO     The CSRF token is missing.
@4000000061fd0e130a2f2b8c [2022-02-04 12:29:13 +0100] [113279] [DEBUG] POST /filtering/task

**Comment by afourmy** [comment]
The scheduler uses the REST API to run a service, and the REST API is not part of the open core version. That's why it doesn't work.

**Comment by buzzzo** [comment]
> The scheduler uses the REST API to run a service, and the REST API is not part of the open core version. That's why it doesn't work.

This means that with v4 is not possible to schedule tasks with opensource version ?

**Comment by afourmy** [comment]
Both the scheduler and the REST API are available in the latest release, v4.2

**Comment by buzzzo** [comment]
Just a suggestion: Please outline the limitations of the opensource version vs paid version on your web site, just to clarify what could be done with it and what could not.
