### ISSUE TITLE
Site view for colocated devices

### ISSUE THREAD

**Issue by doup123** [afourmy/eNMS#386]
Hello, I could not find a way to display colocated devices in a graph as you illustrate in the following image
![image](https://user-images.githubusercontent.com/22396898/191802592-8e77e477-5faa-4dfb-a075-af5703aca926.png)

**Comment by afourmy** [comment]
This has been replaced by the network builder, where you can create any network topology: https://enms.readthedocs.io/en/latest/visualization/network_builder/

![network_builder](https://user-images.githubusercontent.com/16152622/193234532-a9ebe4ab-0e7d-4b83-9dde-5dc2a375816c.png)

In the geographical visualization, colocated devices are only displayed in a table now.
