### ISSUE TITLE
Problem with SQLalchemy

### ISSUE THREAD

**Issue by IgorHolanda12** [afourmy/eNMS#393]
There's a issue with the latest version of sqlalchemy where the the flask instance can't be iniciated. To fix this, change the version on the .txt requirement file to the version before 

sqlalchemy==1.4.46

Error:

Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/root/eNMS-4.2/app.py", line 1, in <module>
    from eNMS.server import server as app  # noqa: F401
  File "/root/eNMS-4.2/eNMS/__init__.py", line 1, in <module>
    from eNMS.controller import controller
  File "/root/eNMS-4.2/eNMS/controller.py", line 33, in <module>
    from eNMS.database import db
  File "/root/eNMS-4.2/eNMS/database.py", line 28, in <module>
    from sqlalchemy.ext.associationproxy import ASSOCIATION_PROXY
ImportError: cannot import name 'ASSOCIATION_PROXY' from 'sqlalchemy.ext.associationproxy' (/usr/local/lib/python3.9/dist-packages/sqlalchemy/ext/associationproxy.py)

**Comment by IgorHolanda12** [comment]
~/eNMS/build/requirements/requirements.txt

apscheduler
argon2-cffi
dicttoxml
dramatiq[redis, watch]
flask
flask_login
flask-socketio
flask_wtf
gitpython
gunicorn
itsdangerous==2.0.1
napalm
ncclient
netmiko==3.4.0
passlib
psutil
redis
ruamel.yaml
sqlalchemy==1.4.46
watchdog
wtforms==2.3.3
xlrd
xlwt
xmltodict

**Comment by Dellink86** [comment]
the File "/root/eNMS-4.2/eNMS/database.py" has two references to 'ASSOCIATION_PROXY' which is the wrong case. I had to change it to association_proxy to get it working.

**Comment by afourmy** [comment]
sqlalchemy now pinned to 1.4.46
