### ISSUE TITLE
topology_import_service librenms

### ISSUE THREAD

**Issue by leonardo-munhoz** [afourmy/eNMS#395]
When I import to enms it brings field values ​​that are fixed and I can't edit the item without adjusting
There is a possibility that these fields are free to be more compatible with import from librenms
![image1](https://user-images.githubusercontent.com/40440690/227385391-51d33e10-c4b4-4439-9542-4e8e81684b65.png)
![image0](https://user-images.githubusercontent.com/40440690/227385460-de1c802a-d56b-4a9a-a056-328d72c3cb4a.png)

**Comment by leonardo-munhoz** [comment]
I will try to add properties.json
and report my results 

 "property_list": {
    "device": {
      **"model": ["Arista", "Cisco", "Linux", "Juniper"],**
      **"operating_system": ["IOS", "IOS-XE", "IOS-XR", "Junos", "EOS", "Linux"],**
      **"vendor": ["Arista", "Cisco", "Juniper", "Linux"]**

**Comment by edaleand** [comment]
Anything from this? I'm getting no vendor info from LibreNMS at all.

**Comment by afourmy** [comment]
if the property lists are empty in the json file, eNMS will automatically use a string field instead of a select field (https://github.com/eNMS-automation/eNMS/blob/public/setup/properties.json#L1490-L1539)
