### ISSUE TITLE
'AssociationProxyExtensionType' is not defined

### ISSUE THREAD

**Issue by SaneiSaya** [afourmy/eNMS#403]
A new install of ver 4.7 is failing with the following error:

enms    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3497, in configure_mappers
enms    |     _configure_registries(_all_registries(), cascade=True)
enms    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3527, in _configure_registries
enms    |     _do_configure_registries(registries, cascade)
enms    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3568, in _do_configure_registries
enms    |     mapper.dispatch.mapper_configured(mapper, mapper.class_)
enms    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 346, in __call__
enms    |     fn(*args, **kw)
enms    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
enms    |     fn(*arg, **kw)
enms    |   File "/eNMS/eNMS/database.py", line 209, in model_inspection
enms    |     association_proxy = AssociationProxyExtensionType.association_proxy
enms    | NameError: name 'AssociationProxyExtensionType' is not defined
enms exited with code 1

Does anyone have a requirements.txt with versions that are working with 4.7?

**Comment by afourmy** [comment]
`AssociationProxyExtensionType` is defined here: https://github.com/eNMS-automation/eNMS/blob/public/eNMS/database.py#L28

In my environment, it works fine with the latest version of SQLAlchemy (2.0.25).

**Comment by SaneiSaya** [comment]
I added that version to my local requirements.txt and it works now. I built a docker image for this version and when it came up it has the version as 4.6.  Let me know if you're interested and I'll post it for testing.
