### ISSUE TITLE
Topology import error ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1129)

### ISSUE THREAD

**Issue by SaneiSaya** [afourmy/eNMS#405]
When trying to do an import from LibreNMS that has a self signed cert, the import fails with this error: 
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1129)

Is there a way to disable the SSL verify?

**Comment by afourmy** [comment]
same problem as here: https://www.reddit.com/r/networking/comments/veqk23/trying_to_integrate_netbox_and_enms/

**Comment by SaneiSaya** [comment]
So we can edit the /eNMS/models/services/miscellaneous/topology_import.py and add the verify_ssl=False like this:

def query_librenms(self):
    devices = custom_http_get(
        f"{self.librenms_address}/api/v0/devices",
        headers={"X-Auth-Token": env.get_password(self.librenms_token)},
        verify_ssl=False  # Disable SSL verification
    ).json()["devices"]
