### ISSUE TITLE
Netmiko Configuration Service error when running a workflow read_timeout

### ISSUE THREAD

**Issue by SaneiSaya** [afourmy/eNMS#407]
Traceback (most recent call last):
  File \"/eNMS/eNMS/runner.py\", line 541, in run_service_job
    results = self.service.job(self, *args)
  File \"/eNMS/eNMS/models/services/configuration/netmiko_configuration.py\", line 42, in job
    netmiko_connection.send_config_set(
TypeError: send_config_set() got an unexpected keyword argument 'read_timeout'

Here is the netmiko version: 
python -c "import netmiko; print(netmiko.__version__)"
3.4.0
eNMS version is 4.6.0

**Comment by afourmy** [comment]
this is not the latest version of netmiko, we don't support older versions

**Comment by SaneiSaya** [comment]
Upgraded netmiko and everything works, thanks!
