### ISSUE TITLE
Adding new ansible playbook files they not showing under new service - No results matched

### ISSUE THREAD

**Issue by SaneiSaya** [afourmy/eNMS#411]
I have uploaded files and scanned the folder for the updated uploaded ansible playbooks. When I try typing in the path I get "No results matched" and can't seem to get it to recognize the new files. It does see the default files.

**Comment by afourmy** [comment]
playbooks should be automatically detected each time an ansible playbook service edit panel is open. the only constraint is that it must be a `.yaml` or `.yml` file

scanning the folder (from the `Files` menu I asssume is what you're saying) is not required

see:
- https://github.com/eNMS-automation/eNMS/blob/public/eNMS/static/js/services/ansible_playbook_service.js#L7-L30
- https://github.com/eNMS-automation/eNMS/blob/5d44513a0a35b29c08b3c985252381efaa9588f8/eNMS/controller.py#L1300-L1308

**Comment by SaneiSaya** [comment]
It doesn't see the folder I created under playbooks either. Do the yml files need to go in the root directory?

**Comment by SaneiSaya** [comment]
I moved the yml files to the playbook  root directory and it auto detects them now.
