### ISSUE TITLE
Make scripts per vendor / os

### ISSUE THREAD

**Issue by longdn84** [afourmy/eNMS#45]
In the scripts menu, currently simple scripts is made with name + content ; so it's should be  to make scripts with vendor / os field (like cisco / ios, ios-xr / asa ; junipe junos ..). From that, we can easy to map for device - scripts

**Comment by afourmy** [comment]
Now that we have a REST call type of script, it doesn't make sense to have vendor/os values for all scripts, but vendor/os SQL columns were added everywhere where it made sense.
