### ISSUE TITLE
Add login without secret password - Just username & password

### ISSUE THREAD

**Issue by JuanmaNT** [afourmy/eNMS#48]
Login with enable root by default (just with one username and password) would be a great improvement.

This will be nice to have in environments where no secret password is enabled and username/password is granted already with level 15.

**Comment by JuanmaNT** [comment]
Hello,

Im refering to both of them - I use a default username & password for automation tasks (not Tacacs) and I can not add it in the config section for a given device.

I need to pass an username & password to the login device that has already level 15 privileges.

Thanks

**Comment by afourmy** [comment]
Ah actually the username and passwords that eNMS are not per-device (for now, that might change if there is a need): it is the exact same username and password than the ones you use to login to eNMS.
So all you have to do is creating a new eNMS account with the same credentials (username / password) than the ones you use to log in to the device.

**Comment by afourmy** [comment]
I made a special page in the docs about how credentials are used in eNMS : 
http://enms.readthedocs.io/en/latest/automation/credentials.html

I will close but you can reopen if it's not clear or I misunderstood your issue.

Thanks
