### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by afourmy** [afourmy/eNMS#51]
Implement a duplication system everywhere where it makes sense:

- duplication of nodes and links
- duplicated of scripts
- duplication of workflows

When the user clicks on `Duplicate`, make a bootstrap modal appear with a unique `Name` field for the name of the duplicate object.

**Comment by xplorn** [comment]
I was just about to writeup a "clone" feature request before finding this.

**Comment by afourmy** [comment]
Done
