### ISSUE TITLE
Flask keys are insecure & in version control

### ISSUE THREAD

**Issue by OzNetNerd** [afourmy/eNMS#52]
At present the Flask keys for prod and test are set to `change-me` and `key`. Furthermore, they're both stored in clear text in the git repo.

https://github.com/afourmy/eNMS/blob/be32c3f75c2bacbd5daa703216d9ca0383ba006d/source/config.py#L22-L29

Keys should instead be retrieved through environment variables and kept out of version control. I'm happy to submit a PR that achieves this.

**Comment by afourmy** [comment]
Sounds good to me.
The only thing is that, at least for the DebugConfig (which is actually the config used for developing the app), please make it default to something in case the environment variable is missing (typically, if you use `os.environ`, then `os.environ.get("thevariable", "thedefaultvalue")`.

The reason why I ask that is that I don't want to have to export a variable everytime I'm working on the app :) For the production config, you can skip the default value if you want.

I'm waiting for your PR then :) Thank you

**Comment by OzNetNerd** [comment]
Yes, a default for `DebugConfig` is the plan. This will give users the option of overwriting it if they so choose.

Speaking of  `DebugConfig`, I'm writing another "issue" at the moment that concerns it. Happy to submit a PR for that one too.

**Comment by afourmy** [comment]
Maybe you mean that `ProductionConfig` is currently never use unless you change the hardcoded `DebugConfig` in `app.py` (https://github.com/afourmy/eNMS/blob/master/source/flask_app.py#L102) ?
Anyway, submit as many PR as necessary :)

**Comment by OzNetNerd** [comment]
Yep, that's the one. It's not a big deal but I figured it would be a quick win for the project :)

PR has been raised: https://github.com/afourmy/eNMS/pull/54

**Comment by afourmy** [comment]
Done.
