### ISSUE TITLE
DebugConfig is used in all situations

### ISSUE THREAD

**Issue by OzNetNerd** [afourmy/eNMS#53]
Though there are `prod` and `debug` classes:

https://github.com/afourmy/eNMS/blob/60155577f34022366572373aa0d24d0f0662afc3/source/config.py#L22-L29

Only the latter is used:

https://github.com/afourmy/eNMS/blob/60155577f34022366572373aa0d24d0f0662afc3/source/flask_app.py#L102

I propose an environment variable be used to determine set the type of deployment. e.g `prod` or `debug`.

I'm happy to submit a PR for this issue too.

**Comment by afourmy** [comment]
Yep, sounds good to me ! (it's not a bug, just that I've been spending too much time on the rest of the app so far to take care of this... I agree it's important though)
Waiting for your PR on this one too then. Thanks !

**Comment by OzNetNerd** [comment]
+1 in regards to not being a bug.

No worries, with any luck I should be able to get it submitted tonight.
