### ISSUE TITLE
Update docs for debug mode

### ISSUE THREAD

**Issue by OzNetNerd** [afourmy/eNMS#55]
Debug docs (https://github.com/afourmy/eNMS/blob/master/docs/base/installation.rst) need to be updated to include the `ENMS_CONFIG_MODE` environment variable created as part of https://github.com/afourmy/eNMS/commit/e206190885f6b3ff1a422e75985c15c86c3fd2ad.

I'm happy to raise a PR for this if you'd like. Do you write the RST files by hand, or do they pull their info from code?

**Comment by afourmy** [comment]
Indeed, the docs need to be updated with this new environment variable, it's awesome if you can take care of that ! I write all RST files by hand, so you would need to manually update the `installation.rst` file.

**Comment by OzNetNerd** [comment]
Sounds great to me @afourmy. Feel free to assign this issue, as well as the one I raised yesterday, to me.

**Comment by afourmy** [comment]
You're right, it's done. I should probably start using the whole labels / milestones system too..

**Comment by afourmy** [comment]
This in done, along with env variables for production mode: database + hashicorp vault setup.
