### ISSUE TITLE
Create a logo for eNMS

### ISSUE THREAD

**Issue by afourmy** [afourmy/eNMS#61]
It would be nice to have a logo for the project at some point. In the docs, the logo would be displayed in the top-left corner under eNMS: http://enms.readthedocs.io/en/latest/#

**Comment by OfWolfAndMan** [comment]
@afourmy any particular literature/movie/game/historical event, or a composite of the aforementioned that you'd think should be a part of this graphical representation?

**Comment by afourmy** [comment]
@OfWolfAndMan Honestly, I've never really thought about it :) I guess the only thing that matters to me is that it's easily identifiable. It doesn't have to be anything complicated.

**Comment by afourmy** [comment]
done with Paint :)
![logo](https://user-images.githubusercontent.com/16152622/46411369-e8e27600-c71b-11e8-9e48-1796c57054b8.png)
