### ISSUE TITLE
node pools

### ISSUE THREAD

**Issue by xplorn** [afourmy/eNMS#65]
The workflow targets nodes based upon map selection.  The case with any map is when you get to some number of 100s of nodes, working with maps is less productive.  It would be useful to have a way to direct scripts to individual nodes or a pool/group of nodes.

Pools could be built by manually selecting from a list and/or applying filter criteria based upon what currently exists for map filters.  Pools would be persistent entities like nodes.

**Comment by afourmy** [comment]
Filters are now persistent. 

Todo:
- implement a system to modify a filter's group of nodes/links.
- filter deletion
- rename filter -> pool

**Comment by afourmy** [comment]
This is now 100% done. You can test the feature and reopen this issue if you find any bug.
