### ISSUE TITLE
openNMS support

### ISSUE THREAD

**Issue by afourmy** [afourmy/eNMS#69]
use openNMS REST API to retrieve the network topology and store it in the database

Docs: https://wiki.opennms.org/wiki/ReST

**Comment by xplorn** [comment]
Thinking about this, OpenNMS admins would probably want a foreign source filter for their imports.

some background-
Provisioning is made up of requisitions that are collections of nodes paired with some policy that governs service detection and other automated augmentation for workflow automation, such as tagging a node for a category automatically based on some criteria, or specify data collection enabled based on interface name parse, etc. The "foreign source" was originally introduced to identify the source from which a list of nodes was created/imported/(requisitioned), such as a CMDB.  I think many people use it to organize their collections of nodes- Network, Servers, Windows Servers, Wireless, Security, Building A, Engineering, Testing, (etc., to fit their organization).

There are quirks about this, for example in OpenNMS using discovery to populate a requisition by default puts nodes into a "" foreignSource unless the configuration is changed to add a name. (this may have changed to foreignSourcce="default" recently in code).  Some nodes may have no foreign source if they were added manually to the system.  I think many of the cases can be found on the demo.opennms.org server (demo.opennms.org/opennms/rest/nodes?limit=0)

So for eNMS with a narrower scope it could make sense to filter a node import from OpenNMS based upon a foreignSource filter in the node parameter of the ReST API.  I would suggest in eNMS that this exists as a filterby kind of constraint and indicated "optional."  

manufacturer in assetRecord is another useful filter key to import nodes by vendor across multiple requisitions.

**Comment by afourmy** [comment]
**from slack, useful info for the implementation:** 

minto [18:09]
 so you're saying that we should have, inside eNMS, a way to let the user filter the results using a specific criteria, say `foreignSource`. But they might want to filter with something else, like `label` or `type`
and if you want for example all nodes with `foreignSource` set to `OpenNMS_ATL`, all you have to do is query the URL `https://demo.opennms.org/opennms/rest/nodes?foreignSource=OpenNMS_ATL`
wouldn't it be better to let the user specify which URL he wants to query, and converts all resulting nodes as eNMS nodes ?
then you can have more complex queries, like combine filters such as `https://demo.opennms.org/opennms/rest/nodes?foreignSource=OpenNMS_ATL&id=67` and I wouldn't have to implement a complex filtering system

esh [18:15]
yeah that makes sense

minto [18:15]
in other words, as I see it, eNMS would ask you for a string (the REST call URL) and that's it. Then I detect automatically whether these are nodes or links, and that's it
OK

esh [18:16]
so your work is to make use of the opennms-specific results to match eNMS fields?

minto [18:17]
I can only import the fields that are part of eNMS model

esh [18:18]
yep

minto [18:19]
for a node: location, longitude, latitude
I don't even see a name ?
I can use the ID of course but...
unless I use `sysName` as name

esh [18:22]
<node label="name"><assetRecord><latitude/><longitude/><manufacturer/><model/></assetRecord></node>
that make sense?
hmm this gets tricky as ip address is in a different table

esh [18:29]
also nodes have multiple interfaces so you want to identify what is called snmpPrimary="P" (primary) interface, which you can see in the example on demo... (edited)
https://demo.opennms.org/opennms/rest/nodes/10/ipinterfaces
which ultimately is how i build csv for creating a spreadsheet for eNMS, by joining node and ipinterfaces tables by nodeid and looking for the issnmpprimary="P" record for that node
location equivalent is "building", ie  <assetRecord><building/></assetRecord> (edited)
(which really should be called location, but... history)

**Comment by afourmy** [comment]
Update the implementation to allow import of a subset of the nodes with specific URL like `https://demo.opennms.org/opennms/rest/nodes?foreignSource=OpenNMS_ATL`

**Comment by afourmy** [comment]
Done
