### ISSUE TITLE
Compare golden/running conf + generate diff

### ISSUE THREAD

**Issue by afourmy** [afourmy/eNMS#73]
Feature request from reddit:
Device Config Compliance - Compare Golden Config with Running Config and generate diffs

**Comment by xplorn** [comment]
Ahh I was going to suggest a config repository feature with the ability to selectively generate diffs between different dated configs.  

The features could creep a lot.  For example, get a config, only stick it in the db if it has changed over previous copy.

**Comment by afourmy** [comment]
This can be done either as a custom service, or via https://github.com/afourmy/eNMS/issues/26

**Comment by afourmy** [comment]
Linked to https://github.com/afourmy/eNMS/issues/104
Implementation on-going

**Comment by afourmy** [comment]
Done via https://github.com/afourmy/eNMS/issues/104
