### ISSUE TITLE
Active Directory Integration for logging into eNMS

### ISSUE THREAD

**Issue by afourmy** [afourmy/eNMS#74]
Feature request from reddit:
Active Directory Integration for logging into eNMS

**Comment by AndersBallegaard** [comment]
I would love to at least give it a shot

**Comment by afourmy** [comment]
@AndersBallegaard Help yourself ! The only thing is that I don't use Windows / Active Directory myself, so I won't be able to help much, let alone test it. But it doesn't matter, if you do something and it works in your environment, I'll merge it :)

**Comment by afourmy** [comment]
Done.
Docs here: https://enms.readthedocs.io/en/latest/base/installation.html#ldap-active-directory-integration
