### ISSUE TITLE
ReST API node import features

### ISSUE THREAD

**Issue by xplorn** [afourmy/eNMS#78]
The API import method should bring over inventory characteristics similar to how the spreadsheet import functions. 

OpenNMS asset fields line up pretty closely.
(opennms assetRecord --> enms map)
- location = lat/long   (done!)
- building = location
- description = description
- modelNumber = model
- manufacturer = vendor
(next two debatable)
- operatingSystem = OS Version
- (not in asset)sysDescription = Operating System

Maybe there is value in checkbox selections for each field that determines whether each field import is attempted to accommodate different use cases?

**Comment by afourmy** [comment]
Done, but I switched OS and OS version i.e
```
operatingSystem = Operating System
(not in asset)sysDescription = OS Version
```

It made more sense based on the values in the online demo of OpenNMS.
