### ISSUE TITLE
Failed to excute python app.py

### ISSUE THREAD

**Issue by karen2016** [afourmy/eNMS#8]
Hi,when I excute python app.py ,it occured a error.
C:\python\net>python app.py
  File "app.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
why.

**Comment by afourmy** [comment]
Hello @karen2016 ,

In app.py the first lines are:

```from __future__ import print_function
from flask import Flask, render_template, request, make_response
from flask_sqlalchemy import SQLAlchemy
# from flask_apscheduler import APScheduler
from werkzeug.utils import secure_filename
from inspect import stack
from os.path import abspath, dirname, join
from datetime import datetime
import json
import logging
import os
import sys
import xlrd```

There can be an ImportError if one of those modules is missing, but I don't understand how there can be a SyntaxError. I've tested with python 2.7 and 3.6 and it's working.
Can you copy/paste the first 10 lines of your app.py file ?
Line 7 should be `from os.path import abspath, dirname, join`, is it so ?

**Comment by karen2016** [comment]
HI，
my app.py is as follows:




Don't I wrongly download? otherwise are you upload wrong?


田洪伟 (Karen Tian)
TEL：+86-10-15210625362
E-Mail：karen.tian@cloudminds.com
Room 1506, Unit C, Wangjing SOHO Tower2,Wangjing Street No.10, Chaoyang District, Beijing China

 
From: Antoine Fourmy
Date: 2017-11-21 15:40
To: afourmy/e-napalm
CC: karen2016; Mention
Subject: Re: [afourmy/e-napalm] Failed to excute python app.py (#8)
Hello @karen2016 ,
In app.py the first lines are:
from flask import Flask, render_template, request, make_response
from flask_sqlalchemy import SQLAlchemy
# from flask_apscheduler import APScheduler
from werkzeug.utils import secure_filename
from inspect import stack
from os.path import abspath, dirname, join
from datetime import datetime
import json
import logging
import os
import sys
import xlrd```
There can be an ImportError if one of those modules is missing, but I don't understand how there can be a SyntaxError. I've tested with python 2.7 and 3.6 and it's working.
Can you copy/paste the first 10 lines of your app.py file ?
Line 7 should be `from os.path import abspath, dirname, join`, is it so ?

**Comment by afourmy** [comment]
@karen2016 there is no file in your latest comment. I don't think it works if you attach a file by email, you would need to drag&drop it directly on github

**Comment by karen2016** [comment]
My app.py   is downloaded from github,you can check it ,.
i don't know why . I tried the exploer download and wget download, it is the same content:


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://assets-cdn.github.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">



  <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/frameworks-c9193575f18b28be82c0a963e144ff6fa7a809dd8ae003a1d1e5979bed3f7f00.css" integrity="sha256-yRk1dfGLKL6CwKlj4UT/b6eoCd2K4AOh0eWXm+0/fwA=" media="all" rel="stylesheet" />
  <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/github-21234bfa8b3c84ce14a2f478a30cfdced799170f4cd683f6589071659970a21b.css" integrity="sha256-ISNL+os8hM4UovR4owz9zteZFw9M1oP2WJBxZZlwohs=" media="all" rel="stylesheet" />
  
  
  <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/site-40d3ebebbd14d73c1a2f449e109a016ab13b3ba29987bc4f8eff487787682a7b.css" integrity="sha256-QNPr670U1zwaL0SeEJoBarE7O6KZh7xPjv9Id4doKns=" media="all" rel="stylesheet" />
  

  <meta name="viewport" content="width=device-width">

i



田洪伟 (Karen Tian)
TEL：+86-10-15210625362
E-Mail：karen.tian@cloudminds.com
Room 1506, Unit C, Wangjing SOHO Tower2,Wangjing Street No.10, Chaoyang District, Beijing China

 
From: Antoine Fourmy
Date: 2017-11-21 15:50
To: afourmy/e-napalm
CC: karen2016; Mention
Subject: Re: [afourmy/e-napalm] Failed to excute python app.py (#8)
@karen2016 there is no file in your latest comment. I don't think it works if you attach a file by email, you would need to drag&drop it directly on github

**Comment by karen2016** [comment]
the app.py is download wrong, i don't no why:
the connects in my downloaded app.py is follows:

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://assets-cdn.github.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">



  <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/frameworks-c9193575f18b28be82c0a963e144ff6fa7a809dd8ae003a1d1e5979bed3f7f00.css" integrity="sha256-yRk1dfGLKL6CwKlj4UT/b6eoCd2K4AOh0eWXm+0/fwA=" media="all" rel="stylesheet" />
  <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/github-21234bfa8b3c84ce14a2f478a30cfdced799170f4cd683f6589071659970a21b.css" integrity="sha256-ISNL+os8hM4UovR4owz9zteZFw9M1oP2WJBxZZlwohs=" media="all" rel="stylesheet" />
  
  
  <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/site-40d3ebebbd14d73c1a2f449e109a016ab13b3ba29987bc4f8eff487787682a7b.css" integrity="sha256-QNPr670U1zwaL0SeEJoBarE7O6KZh7xPjv9Id4doKns=" media="all" rel="stylesheet" />
  

  <meta name="viewport" content="width=device-width">

**Comment by karen2016** [comment]
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://assets-cdn.github.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">



  <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/frameworks-c9193575f18b28be82c0a963e144ff6fa7a809dd8ae003a1d1e5979bed3f7f00.css" integrity="sha256-yRk1dfGLKL6CwKlj4UT/b6eoCd2K4AOh0eWXm+0/fwA=" media="all" rel="stylesheet" />
  <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/github-21234bfa8b3c84ce14a2f478a30cfdced799170f4cd683f6589071659970a21b.css" integrity="sha256-ISNL+os8hM4UovR4owz9zteZFw9M1oP2WJBxZZlwohs=" media="all" rel="stylesheet" />
  
  
  <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/site-40d3ebebbd14d73c1a2f449e109a016ab13b3ba29987bc4f8eff487787682a7b.css" integrity="sha256-QNPr670U1zwaL0SeEJoBarE7O6KZh7xPjv9Id4doKns=" media="all" rel="stylesheet" />
  

  <meta name="viewport" content="width=device-width">

**Comment by afourmy** [comment]
@karen2016 you shouldn't download just the app.py file with the web browser, you're actually downloading the webpage with HTML code.
Instead, you should go [here](https://github.com/afourmy/e-napalm) and click on the `Clone or download` button on the webpage, then you click on "Download zip", you unzip it, and you try to run app.py (`python app.py`). 
You will need to install all dependencies of eNAPALM (with pip or easy_install, for example) (look at the readme in the dependencies section)

**Comment by karen2016** [comment]
@fourmy,Thanks。 i first use the git and download the file by web broswer ,it is wrong. I tried again use your method and it worked .Thanks very much.
