### ISSUE TITLE
custom script configs directory

### ISSUE THREAD

**Issue by xplorn** [afourmy/eNMS#80]
It would be nice to have a scripts/custom.d/ kind of structure to allow custom scripts to live in their own file.  eNMS would have to scan the directory and pick up each script inside.  This might look like:

eNMS/
 + eNMS/
      + scripts/
           + custom.d/
                - example.py
                - nornir_ping.py
                - another_script_times_100.py
                - myScriptLikesCamels.py

Each script would loosely handle its own imports, job definition and parameters.  A global file would have global imports, CustomScript class,  and some magic that automatically populates the create_custom_scripts def.

**Comment by Minituff** [comment]
This is a great idea, I am very interested in this as well.

**Comment by afourmy** [comment]
@xplorn @Minituff 

This is done. Custom scripts must be added to the `scripts/custom_scripts` folder. If you have a lot of custom scripts, you can even add subfolders, subsubfolders... eNMS should automatically detect everything.

Mandatory:
- the dictionnary of parameters must be called `parameters`
- the job must be called `job`

Example of a custom script that does nothing : 

```
parameters = {
    'name': 'script that does nothing',
    'node_multiprocessing': True,
    'description': 'does nothing',
    'vendor': 'none',
    'operating_system': 'all'
}


def job(args):
    # Script that does nothing
    task, node, results = args
    # add your own logic here
    # results is a dictionnary that contains the logs of the script
    results[node.name] = {
        'success': True,
        'logs': 'what will be displayed in the logs'
    }
```

Updated docs : https://enms.readthedocs.io/en/latest/automation/scripts.html#custom-script
You can check in the master branch how it's currently organized : https://github.com/afourmy/eNMS/tree/master/eNMS/scripts/custom_scripts

I will close this issue for now, it's nice if you can find some time to test this new feature.
