### ISSUE TITLE
Script / Workflow Item that invokes a remote ReST API

### ISSUE THREAD

**Issue by shorton3** [afourmy/eNMS#85]
Many modern process workflows include performing a ReST API call as part of the activity. One such example might be using an issue ticketing system's ReST API to create a ticket that work on production nodes is about to begin (and then updating the ticket again when work is completed). Several options appear to exist in eNMS for a remote ReST api call:  
a) create a CustomScript that can be invoked in the workflow (drawback: statically defined parameters, no way to collect user inputs, ie, no form view)
b) use an Ansible script with the Ansible URI module to send ReST (drawback: user needs to be capable of developing an Ansible playbook with those ReST calls)
c) Add addition tab(s) to eNMS for ReST post/patch/put, the URL to send to, and the data to send (via attached json or yaml file).  Additionally, another eNMS tab could support ReST get with a similar form that also includes validation fields similar to the Netmiko Validation script option; in this case, ReST response could be converted to string and matched using regex for validation.

**Comment by afourmy** [comment]
Done & merged in the master branch.
