### ISSUE TITLE
error with command flask run

### ISSUE THREAD

**Issue by sebd44** [afourmy/eNMS#87]
hello! i hope you are doing well
i installed the repository but i'm getting and error
when i run this command after install the requirements and export flask
flask run --host=0.0.0.0

 File "/root/eNMS-master/app.py", line 6, in <module>
    from config import config_dict
  File "/root/eNMS-master/config.py", line 48
    GOTTY_ALLOWED_URLS = [(f'terminal{i + 1}', 8080 + i) for i in range(10)]

to verify that it wasnt my the installation i installted the gentelella.py
and it runs good

* Serving Flask app "gentelella.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to qu

**Comment by afourmy** [comment]
@sebd44 Hi :) Are you using python3.6 ? eNMS supports only python 3.6+, I guess it fails here because of the f-string. If that's not the issue, can you copy/paste the full stacktrace (including the actual error) ?

**Comment by sebd44** [comment]
Hi, nop i wasn't using, so i installed python 3.6 and the error is gone, but i'm missing the import "app"



export FLASK_APP=app.py
flask run --host=0.0.0.0
 * Serving Flask app "app.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not import "app".

**Comment by afourmy** [comment]
@sebd44 Are you running that command in the right folder ? You should run the command in /eNMS, and not in /eNMS/eNMS. The error you have seems to indicate that Flask cannot find `app.py` i.e that you're not in the right folder

**Comment by sebd44** [comment]
so sorry, i didnt realize, 
pwd
/root/eNMS-master

applications  app.pyc    CONTRIBUTING.md  docs  file_transfer  LICENSE.txt  package.json  projects  README.md             requirements.txt  setup.cfg
app.py        config.py  Dockerfile       eNMS  gunicorn.py    migrations   playbooks     readme    requirements_dev.txt  scripts           tests

now i'm running the command to run the app.py
and this is what i get from the output

python3.6 -V
Python 3.6.5

when i run the run flask, i'm still seeing with python2.7 so i think i should run it with python3.6
but how can i change this behavior in the machine, with env? when i type python it should use 3.6 and not the 2.7 that came with the installation

[root@localhost eNMS-master]# flask run --host=0.0.0.0
 * Serving Flask app "app.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/usr/lib64/python2.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/usr/lib64/python2.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/flask/cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/usr/lib64/python2.7/site-packages/flask/cli.py", line 293, in __init__
    self._load_unlocked()
  File "/usr/lib64/python2.7/site-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/lib64/python2.7/site-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/lib64/python2.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/root/eNMS-master/app.py", line 6, in <module>
    from config import config_dict
  File "/root/eNMS-master/config.py", line 48
    GOTTY_ALLOWED_URLS = [(f'terminal{i + 1}', 8080 + i) for i in range(10)]

**Comment by afourmy** [comment]
try `python3 -m flask run -h 0.0.0.0`

**Comment by sebd44** [comment]
hi,
 python3.6 -m flask run -h 0.0.0.0
/bin/python3.6: No module named flask

so i try to install the requirements 
python3.6 -m pip install -r requirements.txt

and now i run the script it showed me no error, it took me the shell prompt
and 

python3.6 -m flask run -h 0.0.0.0
 * Serving Flask app "app.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off

with nmap shows me that is open, but the connection gives me a time out
22/tcp   open  ssh
25/tcp   open  smtp
631/tcp  open  ipp
5000/tcp open  upnp

**Comment by sebd44** [comment]
Hi, 

i'm going to close the issue, i start clean with a previous snapshot

ln -fs /usr/bin/python3.6 /usr/bin/python
python -m pip -r requirements.txt


Thanks a lot for your time and patience
it's a wonderfull app, i will keep learning about this and napalm
have a nice day!

**Comment by afourmy** [comment]
@sebd44 Okay I wasn't sure how to help you because according to what you posted, the application was up and running, I'm glad that it works now :)
I'll close the issue then.
