### ISSUE TITLE
Export topology gives a 404 error

### ISSUE THREAD

**Issue by glenp42** [afourmy/eNMS#88]
Debug logs show:
[2018-10-26 08:31:35 +1100] [27079] [DEBUG] GET /objects/export_topology
127.0.0.1 - - [26/Oct/2018:08:31:35 +1100] "GET /objects/export_topology HTTP/1"

I can't find a file called export_topology anywhere in the git clone.

Glen.

**Comment by afourmy** [comment]
@glenp42 Yes, this feature is broken. Not sure what you're trying to do, but if you want to import a network, you must click on the "Import topology" button.
You have examples of spreadsheets here: https://github.com/afourmy/eNMS/tree/master/projects

No export possible yet.

**Comment by glenp42** [comment]
Thanks for preempting my next question!  
That was what I was looking for, just an example of a topo file.

**Comment by glenp42** [comment]
Can you define the ip address in the spreadsheet?  I don't see it in any examples...

**Comment by glenp42** [comment]
ip_address maybe?

**Comment by afourmy** [comment]
> Can you define the ip address in the spreadsheet? I don't see it in any examples...

I just checked and all spreadsheets have the `ip_address` column.

**Comment by afourmy** [comment]
fixed
