### ISSUE TITLE
After importing a topology, edits of devices are not saved

### ISSUE THREAD

**Issue by glenp42** [afourmy/eNMS#89]
I just imported a simple topo of two switches (attached)

After they load in there are some incorrect fields:

SW-096-01-303-01-01		switch	hpe_procurve	carlton	hpe_procurve	**IOS**		10.207.0.160	**-122.14	37.44**
SW-096-02-304-01-01		switch	hpe_procurve	carlton	hpe_procurve	**IOS**		10.207.0.161	**-122.14	37.44**

On trying to correct them, after I submit the corrected details, I find they are still the same.

Glen.

[carlton.zip](https://github.com/afourmy/eNMS/files/2517447/carlton.zip)

**Comment by afourmy** [comment]
Your spreadsheet is not a valid one: not only does it contain the same line twice (twice the same name, which is not allowed), it also contains the same column twice ("name").
If you import a spreadsheet containing existing devices with updated properties, the properties will be updated but the changes won't be reflected in the table at import time, you'll need to reload the page first. Can you test and confirm this works ?
