### ISSUE TITLE
Docker Quick Start Issue

### ISSUE THREAD

**Issue by gmbytrn** [afourmy/eNMS#92]
With the last release of the afoumy/eNMS on Docker Hub I experience the following error on multiple servers.

**docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./boot.sh\": permission denied": unknown.**

Main Server Specs (from 'docker info'):

Kernel Version: 4.15.18-7-pve
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
Server Version: 18.06.1-ce

**Comment by JackWa** [comment]
Hey @gmbytrn, I was trialling this today and found the same issue.
I've put in a PR to resolve this https://github.com/afourmy/eNMS/pull/94

**Comment by afourmy** [comment]
@JackWa Just merged your PR, thanks !
