### ISSUE TITLE
[feature request] Add networkmap.js to Network vizualisations

### ISSUE THREAD

**Issue by zombah** [afourmy/eNMS#96]
It would be great to have [networkmap.js](https://github.com/otm/networkmap.js/) view for network topology

**Comment by q2dg** [comment]
It seems networkmap.js is pretty abandoned...

**Comment by afourmy** [comment]
This library seems to have been abandoned for a long time now (last commit 3 years ago, author inactive) so it cannot reasonnably be used in eNMS (don't want to have deprecated dependencies).
The same kind of visualization can be done either with D3.js, or with Vis.js, but eNMS focuses on network automation so this kind of visualization is not really a priority (there are betters tools for that than eNMS I guess)
